### ISSUE TITLE
Why isn't Transactional part of the gem?  :)

### ISSUE THREAD

**Issue by odigity** [michaelfairley/method_decorators#19]
I keep here looking for a method decorator gem specifically so I can wrap a bunch of ActiveRecord methods in transactions, only to find exactly what I'm looking for at the bottom of your README.  :)

Why is the Transactional decorator merely an example, and not actually part of the gem like the other four general convenience decorator?

**Comment by michaelfairley** [comment]
Including it wouldn't be a bad idea, but I'm not really all that keen on `method_decorators` being used in production very much, and `Transactional` would also be _slighly_ harder to bake into the library given that is sort-of has a dependency on a 3rd party library.

P.S. Sorry for the extreme delay in answering this. :-/
